"""Normalized streaming events emitted by every LLM provider.

The orchestrator (LangGraph, Layer F) consumes this union and never sees
provider-specific SDK shapes. New providers added later must translate
their native stream into these events.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal


@dataclass(slots=True)
class TextDelta:
    """Incremental text generated by the model."""

    type: Literal["text_delta"] = "text_delta"
    content: str = ""


@dataclass(slots=True)
class ToolCallStart:
    """A tool call has been initiated. arguments stream in via ToolCallDelta."""

    id: str
    name: str
    type: Literal["tool_call_start"] = "tool_call_start"


@dataclass(slots=True)
class ToolCallDelta:
    """Incremental JSON fragment of a tool call's arguments."""

    id: str
    arguments_delta: str
    type: Literal["tool_call_delta"] = "tool_call_delta"


@dataclass(slots=True)
class ToolCallComplete:
    """A tool call is fully assembled and ready to dispatch."""

    id: str
    name: str
    arguments: dict[str, Any] = field(default_factory=dict)
    type: Literal["tool_call_complete"] = "tool_call_complete"


@dataclass(slots=True)
class Usage:
    """Final token counts. Emitted once at end of stream."""

    input_tokens: int
    output_tokens: int
    type: Literal["usage"] = "usage"


@dataclass(slots=True)
class Done:
    """Stream is complete. stop_reason mirrors provider's reason (mapped)."""

    stop_reason: Literal["end_turn", "tool_use", "max_tokens", "stop", "other"]
    type: Literal["done"] = "done"


@dataclass(slots=True)
class StreamError:
    """Recoverable or terminal error from the provider."""

    message: str
    fatal: bool = True
    type: Literal["error"] = "error"


# Discriminated union the orchestrator iterates over.
LLMEvent = (
    TextDelta
    | ToolCallStart
    | ToolCallDelta
    | ToolCallComplete
    | Usage
    | Done
    | StreamError
)
